name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          PORT: 5000
          BASE_PATH: "/home/raman/google-contact-server-side"

      - name: Stop ramanserver service
        run: sudo systemctl stop ramanserver.service

      - name: Clear BASE_PATH directory
        run: sudo rm -rf $BASE_PATH/*

      - name: Recreate BASE_PATH directory
        run: mkdir -p $BASE_PATH

      - name: Create date file
        run: sudo bash -c "date > $BASE_PATH/date.txt"

      - name: Copy files to BASE_PATH
        run: sudo cp -a ./* $BASE_PATH/

      - name: Write environment variable to .env file
        run: echo "${{ secrets.ENV }}" | sudo tee $BASE_PATH/.env > /dev/null

      - name: Install Python venv
        run: sudo apt-get install -y python3-venv

      - name: Create Python virtual environment
        run: sudo python3 -m venv $BASE_PATH/venv

      - name: Install dependencies
        run: sudo $BASE_PATH/venv/bin/pip install -r $BASE_PATH/requirements.txt

      - name: Restart ramanserver service
        run: sudo systemctl restart ramanserver.service
